In [31]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [32]:
import pandas as pd

A = {
    "Buah_A" : ["Apple","Grape","Cherry"],
    "Terjual" : [15, 20,10]
}

B = {
    "Buah_B" : ["Strawberry", "Pear","Avocado"],
    "Terjual" : [20,22,18]
}

In [36]:
print(f"{A}\n{B}")

{'Buah_A': ['Apple', 'Grape', 'Cherry'], 'Terjual': [15, 20, 10]}
{'Buah_B': ['Strawberry', 'Pear', 'Avocado'], 'Terjual': [20, 22, 18]}


In [41]:
Table_A = pd.DataFrame(A)
Table_B = pd.DataFrame(B)
print(f"{Table_A}\n{Table_B}")

   Buah_A  Terjual
0   Apple       15
1   Grape       20
2  Cherry       10
       Buah_B  Terjual
0  Strawberry       20
1        Pear       22
2     Avocado       18


In [34]:
print(f"tipe data A adalah {type(A)} \ntipe data table_A adalah {type(Table_A)} \ntipe data B adalah {type(B)}\ntipe data table_B adalah {type(Table_B)}")

tipe data A adalah <class 'dict'> 
tipe data table_A adalah <class 'pandas.core.frame.DataFrame'> 
tipe data B adalah <class 'dict'>
tipe data table_B adalah <class 'pandas.core.frame.DataFrame'>


In [24]:
import numpy as np

In [30]:
Angka = np.random.randint(1,10,[10,10])
print(f"{Angka}\n{type(Angka)}")

[[9 4 2 4 1 8 6 5 2 8]
 [2 6 9 9 1 6 8 6 6 1]
 [6 5 1 1 5 2 4 3 9 1]
 [8 1 3 6 4 8 7 8 1 1]
 [8 9 8 2 9 4 5 2 9 1]
 [4 5 2 3 7 4 5 6 9 9]
 [7 1 5 4 8 4 9 2 4 4]
 [8 4 8 4 6 7 8 5 2 8]
 [1 7 4 9 6 6 3 9 6 1]
 [4 5 8 6 7 6 2 9 5 7]]
<class 'numpy.ndarray'>


In [43]:
Angka_Tensor = tf.random.shuffle(Angka)
print(f"{Angka_Tensor}\n{type(Angka_Tensor)}")

[[1 7 4 9 6 6 3 9 6 1]
 [7 1 5 4 8 4 9 2 4 4]
 [8 4 8 4 6 7 8 5 2 8]
 [9 4 2 4 1 8 6 5 2 8]
 [6 5 1 1 5 2 4 3 9 1]
 [8 9 8 2 9 4 5 2 9 1]
 [2 6 9 9 1 6 8 6 6 1]
 [4 5 2 3 7 4 5 6 9 9]
 [8 1 3 6 4 8 7 8 1 1]
 [4 5 8 6 7 6 2 9 5 7]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [73]:
Tensor_baru = tf.random.uniform([10,10],minval=1,maxval=10)
Tensor_baru

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[8.59947  , 2.4828775, 2.6922014, 4.3278146, 9.848661 , 4.070772 ,
        6.17448  , 7.6065407, 2.734737 , 3.9130454],
       [3.9367142, 4.415221 , 7.2498484, 1.5104727, 5.5744324, 6.852828 ,
        3.643642 , 3.229949 , 1.903766 , 5.8255043],
       [8.701809 , 2.3831015, 4.347874 , 5.6199775, 8.076658 , 5.1532407,
        2.6870515, 1.0603218, 8.695088 , 8.426857 ],
       [6.51717  , 6.0765085, 6.1761475, 9.0964   , 5.6799903, 6.612767 ,
        4.106084 , 3.506784 , 5.214775 , 6.160541 ],
       [4.350516 , 6.946822 , 5.61944  , 9.738677 , 1.0399435, 1.7795894,
        1.2935463, 3.9597318, 7.698891 , 2.2527814],
       [7.9415097, 6.9334   , 8.488716 , 2.5027957, 1.3794382, 9.8299265,
        6.1816063, 9.208525 , 2.2787561, 2.3061018],
       [2.2542834, 3.9740129, 9.520844 , 8.914557 , 7.5970016, 6.917571 ,
        2.1219711, 9.732755 , 8.507783 , 7.3385086],
       [5.6833687, 2.9352021, 3.8178935, 7.38334  , 3.9931285

In [79]:
print(f"Nilai tertinggi matrix Angka : {tf.argmax(Angka)}\nNilai tertinggi matrix Angka : {tf.argmax(Angka_Tensor)}\nNilai tertinggi matrix Angka : {tf.argmax(Tensor_baru)}")
print(f"Nilai terendah matrix Angka : {tf.argmin(Angka)}\nNilai terendah matrix Angka : {tf.argmin(Angka_Tensor)}\nNilai terendah matrix Angka : {tf.argmin(Tensor_baru)}")

Nilai tertinggi matrix Angka : [0 4 1 1 4 0 6 8 2 5]
Nilai tertinggi matrix Angka : [3 5 6 0 5 3 1 0 4 7]
Nilai tertinggi matrix Angka : [9 4 6 4 0 5 8 6 8 8]
Nilai terendah matrix Angka : [8 3 2 2 0 2 9 4 3 1]
Nilai terendah matrix Angka : [0 1 4 4 3 4 9 1 8 0]
Nilai terendah matrix Angka : [6 8 0 1 4 4 4 2 1 4]
