In [1]:
import numpy as np
import pandas as pd

In [15]:
A = np.zeros(10)
B = np.ones(10)

In [16]:
print(type(A))
print(type(B))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
print(A)
print(B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
Variable_A = {"KUE_A" : A,
              "KUE_B" : B}

type(Variable_A)

dict

In [19]:
Hasil_Data = pd.DataFrame(Variable_A)
Hasil_Data

KUE_A  KUE_B
0    0.0    1.0
1    0.0    1.0
2    0.0    1.0
3    0.0    1.0
4    0.0    1.0
5    0.0    1.0
6    0.0    1.0
7    0.0    1.0
8    0.0    1.0
9    0.0    1.0

In [20]:
Buah = {
    "buah_pertama" : ['Apple','Anggur','Cherry'],
    "buah_kedua" : ["Blueberry", "Durian", "Kapulaga"]
}

In [21]:
Buah_Frame = pd.DataFrame(Buah)
Buah_Frame

buah_pertama buah_kedua
0        Apple  Blueberry
1       Anggur     Durian
2       Cherry   Kapulaga

In [23]:
Gabungan = [Hasil_Data,Buah_Frame]
Gabungan = pd.concat(Gabungan)
Gabungan

KUE_A  KUE_B buah_pertama buah_kedua
0    0.0    1.0          NaN        NaN
1    0.0    1.0          NaN        NaN
2    0.0    1.0          NaN        NaN
3    0.0    1.0          NaN        NaN
4    0.0    1.0          NaN        NaN
5    0.0    1.0          NaN        NaN
6    0.0    1.0          NaN        NaN
7    0.0    1.0          NaN        NaN
8    0.0    1.0          NaN        NaN
9    0.0    1.0          NaN        NaN
0    NaN    NaN        Apple  Blueberry
1    NaN    NaN       Anggur     Durian
2    NaN    NaN       Cherry   Kapulaga

In [24]:
import tensorflow as tf

In [46]:
Jumlah = tf.ones([10,10])
print(Jumlah)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


In [67]:
Angka = tf.random.uniform([5,5],minval=15,maxval=20)
print(Angka)

tf.Tensor(
[[19.644758 17.502335 16.486982 19.073675 15.493136]
 [15.119223 17.529871 15.389586 18.015015 16.795189]
 [15.397329 18.280024 17.93293  17.781937 15.563813]
 [17.910244 17.904602 17.55832  16.541443 15.524832]
 [16.938    19.173826 19.885305 16.64646  15.632371]], shape=(5, 5), dtype=float32)


In [69]:
Tensor = tf.math.multiply(Jumlah,5)
print(Tensor)

tf.Tensor(
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]], shape=(10, 10), dtype=float32)


In [56]:
Tensor.numpy()

array([[ 4.2290115 ,  9.17776   ,  7.2247095 , 16.25836   ,  3.9540462 ,
         7.2467136 , 19.193092  , 14.494022  ,  5.4826517 , 15.422998  ],
       [ 6.6463947 ,  8.208944  ,  7.2200956 ,  7.6109304 ,  2.2867024 ,
         2.4765172 ,  1.5100417 , 19.83197   ,  0.58322465, 13.688443  ],
       [ 5.3876605 , 13.3860855 , 18.993765  , 12.6686945 ,  9.282696  ,
        12.503606  ,  9.567929  ,  6.787063  ,  9.533276  , 12.800531  ],
       [ 7.90154   , 12.5205965 , 13.909042  , 16.96493   ,  1.2566781 ,
         1.7354221 , 14.57093   , 15.468687  ,  2.4299593 ,  2.905006  ],
       [ 8.965278  , 12.834835  , 19.385319  , 12.174019  ,  7.4044027 ,
        19.314844  ,  1.8263307 , 12.764905  ,  7.5192213 ,  2.7897873 ],
       [10.8218975 ,  5.9896593 , 11.162165  , -0.3248093 ,  0.951051  ,
         5.390787  , 12.982238  , -0.70760846,  8.292732  ,  5.071464  ],
       [15.271526  , 12.1716    , 11.859831  ,  0.9240719 , 15.1478195 ,
         4.321392  ,  2.1520398 ,  2.8608484 

In [65]:
Tensor.numpy()

array([[20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.]], dtype=float32)